version: '2.1'
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    depends_on:
      - mqtt
    container_name: zigbee2mqtt 
    restart: always
    volumes:
      - /mnt/smarthouse/zigbee2mqtt/:/app/data/
    devices:
      - "/dev/ttyACM0"
    networks:
        - hass
  mqtt:
    image: eclipse-mosquitto
    ports:
       - 1883:1883
       - 9001:9001 
    networks:
        - hass
    volumes:
      - /mnt/smarthouse/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  hass:
    image: homeassistant/home-assistant
    depends_on:
      - zigbee2mqtt
    ports:
      - "5123:8123"
    networks:
      - hass
    volumes:
      - /mnt/smarthouse/homeassistant:/config
      - "/etc/localtime:/etc/localtime:ro"
networks:
  hass:
    driver: overlay
  
